steps:
  - name: python
    entrypoint: pip
    args: ['install', '-r', 'requirements.txt', '--user']

  - name: python
    entrypoint: python
    args: ['compile.py']

  - name: python
    entrypoint: python
    args: ['trigger.py']
