steps:
  - name: python
    entrypoint: pip
    args: ['install', '-r', './pipeline/marketing_custom_from_docker/requirements.txt', '--user']

  - name: python
    entrypoint: python
    args: ['./pipeline/marketing_custom_from_docker/compile.py']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', './pipeline/marketing_custom_from_docker/marketing_custom_pipeline.json', 'gs://mitochondrion-bucket-sg/pipelines/']

  - name: python
    entrypoint: python
    args: ['./pipeline/marketing_custom_from_docker/trigger.py']

options:
  logging: CLOUD_LOGGING_ONLY