build:
	docker build -t asia-southeast2-docker.pkg.dev/mitochondrion-project-344303/vertex-repo/marketing_lgbm:v1 .

push:
	docker push asia-southeast2-docker.pkg.dev/mitochondrion-project-344303/vertex-repo/marketing_lgbm:v1

all: build push
